# Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG ZED_SDK_MAJOR=4
ARG ZED_SDK_MINOR=0

# zed-ros2-wrapper dependencies
RUN --mount=type=cache,target=/var/cache/apt \
apt-get update && apt-get install -y \
    libgeographic-dev  \
    ros-humble-geographic-info \
    ros-humble-nmea-msgs \
    ros-humble-robot-localization \
    ros-humble-xacro

# The zed installation script expects to be run as non-root user and needs the USER ENV variable to be set
ENV USER=${USERNAME}
USER ${USERNAME}

COPY scripts/install-zed-x86_64.sh /opt/zed/install-zed-x86_64.sh
COPY scripts/install-zed-aarch64.sh /opt/zed/install-zed-aarch64.sh

RUN --mount=type=cache,target=/var/cache/apt \
  if [ "$(uname -m)" = "x86_64" ]; then \
    sudo chmod +x /opt/zed/install-zed-x86_64.sh; \
    /opt/zed/install-zed-x86_64.sh; \
  else \
    sudo chmod +x /opt/zed/install-zed-aarch64.sh; \
    /opt/zed/install-zed-aarch64.sh; \
  fi

# Revert to root user
USER root

# TODO: MOVE TO SEPERATE DOCKER FILE THESE ARE BIGBOT DEPENCIES
RUN pip install --no-cache-dir \
    depthai==2.29.0.0 \
    asyncpg \
    psycopg2 \
    fastapi==0.110.0 \
    uvicorn[standard] \
    asyncpg==0.29.0 \
    paho-mqtt==1.6.1 \
    ultralytics --no-deps\
    dill \
    lap \
    async_timeout \
    websockets \ 
    httpx \
    redis

# Enable GPS access
RUN chmod 666 /dev/ttyACM0 || true

# Building of torchvision version for torch 2.2.0 : https://forums.developer.nvidia.com/t/pytorch-for-jetson/72048
ENV USE_CUDA=1 
ENV USE_CUDNN=1
ENV USE_MKLDNN=1
ENV TORCH_CUDA_ARCH_LIST="8.7"
ENV FORCE_CUDA=1
ENV FORCE_MPS=1

# Install system-level dependencies for torchvision build
RUN apt-get update && apt-get install -y \
    libjpeg-dev \
    zlib1g-dev \
    libpython3-dev \
    libopenblas-dev \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    && rm -rf /var/lib/apt/lists/*

# Clone and build torchvision from source
RUN git clone --branch v0.17.1 https://github.com/pytorch/vision.git && \
    cd vision && \
    export BUILD_VERSION=0.17.1 && \
    python3 setup.py install && \
    cd .. && \
    rm -rf vision


# # Copy hotplug script for udev rules
RUN mkdir -p /opt/bigbot/
COPY udev_rules/99-bigbot-libusb-custom.rules /etc/udev/rules.d/99-bigbot-libusb-custom.rules

# Install apt installations
RUN --mount=type=cache,target=/var/cache/apt \
apt-get update && apt-get install -y \
    ros-humble-ublox-gps  \
    ros-humble-geographic-info \
    ros-humble-isaac-ros-jetson-stats \
    ros-humble-isaac-ros-stereo-image-proc \
    ros-humble-xacro \
    ros-humble-tf-transformations \
    python3-libnvinfer

# Install ROS2 ZED Wrapper deps
RUN --mount=type=cache,target=/var/cache/apt \
apt-get update && apt-get install -y \
    ros-humble-point-cloud-transport-plugins \
    ros-humble-draco-point-cloud-transport \
    ros-humble-zlib-point-cloud-transport \
    ros-humble-zstd-point-cloud-transport \
    ros-humble-point-cloud-transport \
    ros-humble-ffmpeg-image-transport \
    ros-humble-ffmpeg-encoder-decoder \
    ros-humble-zed-msgs \ 
    ros-humble-cob-srvs

# Install Isaac ROS Core deps
RUN --mount=type=cache,target=/var/cache/apt \
apt-get update && apt-get install -y \
    ros-humble-isaac-ros-test \
    ros-humble-isaac-ros-h264-decoder \
    ros-humble-isaac-ros-managed-nitros \
    ros-humble-isaac-ros-image-proc

# Install Isaac ROS Visual SLAM & Related Deps
RUN --mount=type=cache,target=/var/cache/apt \
apt-get update && apt-get install -y \
    ros-humble-isaac-ros-managed-nitros \
    ros-humble-isaac-ros-test \
    ros-humble-isaac-ros-launch-utils \
    ros-humble-isaac-ros-visual-slam \
    ros-humble-nova-carter-navigation \
    ros-humble-isaac-ros-dnn-image-encoder \
    ros-humble-isaac-ros-triton \
    ros-humble-isaac-ros-unet \
    ros-humble-isaac-ros-peoplesemseg-models-install

# Set working directory back to the root
WORKDIR /

