# Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG ZED_SDK_MAJOR=4
ARG ZED_SDK_MINOR=0

# zed-ros2-wrapper dependencies
RUN --mount=type=cache,target=/var/cache/apt \
apt-get update && apt-get install -y \
    libgeographic-dev  \
    ros-humble-geographic-info \
    ros-humble-nmea-msgs \
    ros-humble-robot-localization \
    ros-humble-xacro

# The zed installation script expects to be run as non-root user and needs the USER ENV variable to be set
ENV USER=${USERNAME}
USER ${USERNAME}

COPY scripts/install-zed-x86_64.sh /opt/zed/install-zed-x86_64.sh
COPY scripts/install-zed-aarch64.sh /opt/zed/install-zed-aarch64.sh

RUN --mount=type=cache,target=/var/cache/apt \
  if [ "$(uname -m)" = "x86_64" ]; then \
    sudo chmod +x /opt/zed/install-zed-x86_64.sh; \
    /opt/zed/install-zed-x86_64.sh; \
  else \
    sudo chmod +x /opt/zed/install-zed-aarch64.sh; \
    /opt/zed/install-zed-aarch64.sh; \
  fi

# Revert to root user
USER root

# TODO: MOVE TO SEPERATE DOCKER FILE THESE ARE BIGBOT DEPENCIES
RUN pip install --no-cache-dir \
    numpy==1.23 \
    depthai==2.29.0.0 \
    asyncpg \
    iai-gxipy==2.0.2105.9261 \
    psycopg2 \
    fastapi==0.110.0 \
    uvicorn[standard] \
    asyncpg==0.29.0 \
    paho-mqtt==1.6.1 \
    ultralytics \
    websockets \ 
    httpx

# # Copy hotplug script for udev rules
RUN mkdir -p /opt/bigbot/
COPY udev_rules/99-bigbot-libusb-custom.rules /etc/udev/rules.d/99-bigbot-libusb-custom.rules

# Set working directory
WORKDIR /opt/daheng_sdk

# Download the Daheng SDK
RUN wget -O Galaxy_Linux-armhf.zip "https://hs.va-imaging.com/hubfs/Supportshare/Daheng%20SDK/Galaxy_Linux-armhf_Gige-U3_32bits-64bits_1.5.2303.9202.zip"
RUN unzip Galaxy_Linux-armhf.zip
WORKDIR /opt/daheng_sdk/Galaxy_Linux-armhf_Gige-U3_32bits-64bits_1.5.2303.9202
RUN chmod +x ./Galaxy_camera.run
RUN ./Galaxy_camera.run

# Install apt installations
RUN --mount=type=cache,target=/var/cache/apt \
apt-get update && apt-get install -y \
    ros-humble-ublox-gps  \
    ros-humble-geographic-info \
    ros-humble-isaac-ros-jetson-stats \
    ros-humble-isaac-ros-stereo-image-proc \
    ros-humble-xacro \
    ros-humble-tf-transformations \
    python3-libnvinfer

# Install ROS2 ZED Wrapper deps
RUN --mount=type=cache,target=/var/cache/apt \
apt-get update && apt-get install -y \
    ros-humble-point-cloud-transport-plugins \
    ros-humble-draco-point-cloud-transport \
    ros-humble-zlib-point-cloud-transport \
    ros-humble-zstd-point-cloud-transport \
    ros-humble-point-cloud-transport \
    ros-humble-ffmpeg-image-transport \
    ros-humble-ffmpeg-encoder-decoder \
    ros-humble-zed-msgs \ 
    ros-humble-cob-srvs

# Install Isaac ROS Core deps
RUN --mount=type=cache,target=/var/cache/apt \
apt-get update && apt-get install -y \
    ros-humble-isaac-ros-test \
    ros-humble-isaac-ros-h264-decoder \
    ros-humble-isaac-ros-managed-nitros \
    ros-humble-isaac-ros-image-proc

# Install Isaac ROS Visual SLAM & Related Deps
RUN --mount=type=cache,target=/var/cache/apt \
apt-get update && apt-get install -y \
    ros-humble-isaac-ros-managed-nitros \
    ros-humble-isaac-ros-test \
    ros-humble-isaac-ros-launch-utils \
    ros-humble-isaac-ros-visual-slam \
    ros-humble-nova-carter-navigation \
    ros-humble-isaac-ros-dnn-image-encoder \
    ros-humble-isaac-ros-triton \
    ros-humble-isaac-ros-unet \
    ros-humble-isaac-ros-peoplesemseg-models-install

# Set working directory back to the root
WORKDIR /

